# Generated by Django 4.0.6 on 2022-09-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinesetest', '0007_remove_word_solved_solve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='solved',
        ),
    ]
