# Generated by Django 3.2.6 on 2021-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
