# Generated by Django 3.2.6 on 2021-08-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinesetest', '0002_word_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='word',
            name='solved',
        ),
    ]
