# Generated by Django 3.2.6 on 2021-08-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinesetest', '0003_auto_20210829_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinesetest.word')),
            ],
        ),
    ]
