# Generated by Django 3.2.6 on 2021-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinesetest', '0004_auto_20210829_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hsk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
